# Generated by Django 2.0.4 on 2018-05-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oshodiscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'Scrumy Goals'},
        ),
    ]
