# Generated by Django 2.0.4 on 2018-04-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_status', models.CharField(choices=[('V', 'Verified'), ('P', 'Pending'), ('I', 'In-Progress'), ('D', 'Done')], default='I', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_type', models.CharField(choices=[('D', 'Daily Goals'), ('W', 'Weekly Goals')], default='D', max_length=2)),
                ('Desciption', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=200)),
                ('Age', models.IntegerField(max_length=20)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Role', models.CharField(choices=[('OW', 'Owner'), ('AD', 'Admin'), ('QA', 'Quality-analyst'), ('DV', 'Developer')], default='DV', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jimohscrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='goal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jimohscrumy.ScrumyGoal'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jimohscrumy.ScrumyUser'),
        ),
    ]
