# Generated by Django 2.0.4 on 2018-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimohscrumy', '0002_auto_20180428_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoal',
            name='title',
            field=models.CharField(default='New goal', max_length=200),
        ),
    ]
