# Generated by Django 2.0.4 on 2018-04-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jimohscrumy', '0005_auto_20180430_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoal',
            name='status',
        ),
    ]
