# Generated by Django 2.0.4 on 2018-05-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jimohscrumy', '0007_scrumygoal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='jimohscrumy.ScrumyUser'),
        ),
    ]
