# Generated by Django 2.0.4 on 2018-05-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jimohscrumy', '0008_auto_20180507_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usern', to='jimohscrumy.ScrumyUser'),
        ),
    ]
