# Generated by Django 2.0.4 on 2018-05-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jimohscrumy', '0010_auto_20180507_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoal',
            name='status',
        ),
    ]
