# Generated by Django 2.0.5 on 2018-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwanzescrumy', '0002_auto_20180505_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
