# Generated by Django 2.0.4 on 2018-05-04 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('verify_by', models.TextField(blank=True, max_length=30, null=True)),
                ('move_by', models.TextField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_status', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(('WT',), 'Weekly Task'), (('DT',), 'Daily Task'), (('VY',), 'Verify'), ('DE', 'Done')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Own', 'Owner'), ('Adm', 'Administrator'), ('QA', 'Quality Analyst'), ('Dev', 'Developer')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odekhiranscrumy.GoalStatus'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odekhiranscrumy.User'),
        ),
    ]
