# Generated by Django 2.0.4 on 2018-05-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='move_on',
            field=models.TextField(blank=True, null=True, verbose_name='Move on'),
        ),
    ]
