# Generated by Django 2.0.4 on 2018-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0003_auto_20180504_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='move_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='move_on',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Move on'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='verify_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
