# Generated by Django 2.0.4 on 2018-05-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0005_auto_20180504_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='task',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='move_by',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='move_on',
        ),
    ]
