# Generated by Django 2.0.4 on 2018-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0006_auto_20180505_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='name',
            field=models.CharField(default='scrumystatus', max_length=255),
        ),
    ]
