# Generated by Django 2.0.4 on 2018-05-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0007_goalstatus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='description',
            new_name='task',
        ),
    ]
