# Generated by Django 2.0.4 on 2018-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0008_auto_20180505_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalStatus',
            new_name='Status',
        ),
    ]
