# Generated by Django 2.0.4 on 2018-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0009_auto_20180505_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AddField(
            model_name='goal',
            name='task_id',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
