# Generated by Django 2.0.4 on 2018-05-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0010_auto_20180505_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
