# Generated by Django 2.0.4 on 2018-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odekhiranscrumy', '0011_remove_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
