# Generated by Django 2.0.4 on 2018-05-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adesokanscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalstatus',
            name='gstatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adesokanscrumy.GoalStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='category',
            field=models.CharField(choices=[('1', 'Verify'), ('2', 'Done'), ('3', 'Weekly Target'), ('4', 'Daily Target')], max_length=100),
        ),
    ]
