# Generated by Django 2.0.4 on 2018-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='scrumyuser',
            new_name='scrumyuser_id',
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('V', 'Verified')], max_length=50),
        ),
    ]
