# Generated by Django 2.0.4 on 2018-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0005_auto_20180426_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalstatus',
            name='status',
            field=models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('V', 'Verified')], max_length=50),
        ),
    ]
