# Generated by Django 2.0.4 on 2018-04-27 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0006_auto_20180427_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='text',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='published_date',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(default='not been moved yet', max_length=50),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='task_id',
            field=models.IntegerField(default=419),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='time_of_status_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goalstatus',
            field=models.ForeignKey(blank=True, default=419, null=True, on_delete=django.db.models.deletion.PROTECT, to='lagscrumy.GoalStatus'),
        ),
    ]
