# Generated by Django 2.0.4 on 2018-04-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0007_auto_20180427_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstatus',
            name='role',
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='verified_by',
            field=models.CharField(choices=[('O', 'OWNER'), ('D', 'DEVELOPER'), ('QA', 'QUALITY ANALYST'), ('A', 'ADMIN')], default='ADMIN', max_length=30),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(default='OWNER', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goalstatus',
            field=models.ForeignKey(blank=True, default=400, null=True, on_delete=django.db.models.deletion.PROTECT, to='lagscrumy.GoalStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='task_id',
            field=models.IntegerField(default=400),
        ),
    ]
