# Generated by Django 2.0.4 on 2018-04-28 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0010_auto_20180427_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='password',
            field=models.CharField(default='Enter Your Password Here', max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='title',
            field=models.CharField(default='Lab...', max_length=200),
        ),
    ]
