# Generated by Django 2.0.4 on 2018-04-28 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagscrumy', '0011_auto_20180428_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumyuser',
            name='password2',
            field=models.CharField(default='Enter Your Password Again', max_length=50, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
