# Generated by Django 2.0.4 on 2018-04-27 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done')], max_length=1)),
                ('completed_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('verified_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('DG', 'Daily Goals'), ('WG', 'Weekly Goals')], max_length=2)),
                ('goal_description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('Q', 'Quality Analyst'), ('D', 'Developer')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talabiscrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talabiscrumy.ScrumyGoals'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talabiscrumy.ScrumyUser'),
        ),
    ]
