# Generated by Django 2.0.4 on 2018-04-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_no', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasugbaScrumy.ScrumyUser'),
        ),
    ]
