# Generated by Django 2.0.4 on 2018-05-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0003_scrumygoals_scrumy_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'permissions': (('anywhere_to_anywhere', 'Can move from anywhere to anywhere'), ('DT_to_verify', 'Can move from DT to Verify'), ('verify_t0_done', 'Can move from verify to Done'), ('WG_to_DT', 'Can move from WG to DT')), 'verbose_name_plural': 'Scrumy Goals'},
        ),
        migrations.AlterModelOptions(
            name='scrumystatus',
            options={'verbose_name_plural': 'Scrumy Status'},
        ),
        migrations.AlterModelOptions(
            name='scrumyuser',
            options={'verbose_name_plural': 'Scrumy Users'},
        ),
    ]
