# Generated by Django 2.0.4 on 2018-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0014_auto_20180506_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_type',
            field=models.CharField(choices=[('dg', 'daily goals'), ('wg', 'weekly goals'), ('cg', 'completed goals')], default='DT', max_length=64),
        ),
    ]
