# Generated by Django 2.0.5 on 2018-05-13 20:13

from django.db import migrations, models
import django.db.models.deletion
import fasugbaScrumy.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
            },
        ),
        migrations.CreateModel(
            name='ScrumyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Scrumy Status',
            },
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, validators=[fasugbaScrumy.validators.validate_username_length, fasugbaScrumy.validators.validate_username_alphadigits], verbose_name='User name')),
                ('first_name', models.CharField(max_length=100, validators=[fasugbaScrumy.validators.validate_lastname_length], verbose_name='Last name')),
                ('last_name', models.CharField(max_length=100, validators=[fasugbaScrumy.validators.validate_firstname_length], verbose_name='First name')),
                ('password1', models.CharField(max_length=30, validators=[fasugbaScrumy.validators.validate_password_length, fasugbaScrumy.validators.validate_password_digit, fasugbaScrumy.validators.validate_password_uppercase])),
                ('password2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15, validators=[fasugbaScrumy.validators.validate_phonenumber])),
                ('birth_date', models.DateField(verbose_name='What is your birth date?')),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(default='Nigeria', max_length=100)),
                ('scrumy_user_role', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'QA - Quality Analyst'), (4, 'Developer')])),
            ],
            options={
                'verbose_name_plural': 'Scrumy Users',
                'permissions': (('anywhere_to_anywhere', 'Can move from anywhere to anywhere'), ('DT_to_verify', 'Can move from DT to Verify'), ('verify_t0_done', 'Can move from verify to Done'), ('WG_to_DT', 'Can move from WG to DT')),
            },
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasugbaScrumy.ScrumyStatus'),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fasugbaScrumy.ScrumyUser'),
        ),
    ]
