# Generated by Django 2.0.5 on 2018-05-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumyuser',
            name='scrumy_user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer'), (2, 'Admin'), (3, 'QA - Quality Analyst'), (4, 'Owner')]),
        ),
    ]
