# Generated by Django 2.0.4 on 2018-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
