# Generated by Django 2.0.4 on 2018-04-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fasugbaScrumy', '0002_scrumystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fasugbaScrumy.ScrumyStatus'),
            preserve_default=False,
        ),
    ]
