# Generated by Django 2.0.5 on 2018-05-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwanzescrumy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoal',
            old_name='status_id',
            new_name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nwanzescrumy.GoalStatus'),
        ),
    ]
