<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-05-07 01:49
=======
# Generated by Django 2.0.4 on 2018-04-22 19:36
>>>>>>> e0bf16533a58cb488fe42653b263fa1dd71ad51a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('V', 'Verified'), ('D', 'Done')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('WG', 'Weekly Goal'), ('DT', 'Daily Task')], max_length=2)),
                ('goal_description', models.TextField()),
<<<<<<< HEAD
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyscrumy.GoalStatus')),
=======
                ('date_created', models.DateTimeField(verbose_name='dateCreated')),
                ('date_updated', models.DateTimeField(verbose_name='dateUpdated')),
>>>>>>> e0bf16533a58cb488fe42653b263fa1dd71ad51a
            ],
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('O', 'Owner'), ('A', 'Admin'), ('Q', 'Quality Analyst'), ('D', 'Developer')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
<<<<<<< HEAD
            name='user_id',
=======
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyscrumy.ScrumyUser'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyscrumy.ScrumyGoals'),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='verified_by',
>>>>>>> e0bf16533a58cb488fe42653b263fa1dd71ad51a
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyscrumy.ScrumyUser'),
        ),
    ]
