# Generated by Django 2.0.4 on 2018-05-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greyscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2018-05-07'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='date_updated',
            field=models.DateField(auto_now_add=True, default='2018-05-07'),
            preserve_default=False,
        ),
    ]
