# Generated by Django 2.0.4 on 2018-04-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greyscrumy', '0002_auto_20180422_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumygoals',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='goalstatus',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='greyscrumy.GoalStatus'),
            preserve_default=False,
        ),
    ]
