# Generated by Django 2.0.4 on 2018-05-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oderascrumy', '0013_auto_20180429_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_type',
            field=models.CharField(choices=[('1', 'daily goals'), ('2', 'weekly goals'), ('3', 'completed goals')], default='DT', max_length=64),
        ),
    ]
