# Generated by Django 2.0.4 on 2018-04-30 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Verify'), ('2,', 'Done'), ('3', 'Weekly Target'), ('4', 'Daily Target')], max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=200)),
                ('date_completed', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Goal Status',
            },
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('desc', models.TextField(default='achieve')),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
            },
        ),
        migrations.CreateModel(
            name='ScrumyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('roles', models.CharField(choices=[('1', 'Owner'), ('2', 'ADMIN'), ('3', 'QualityAssurace'), ('4', 'Developer')], max_length=200)),
                ('gender', models.CharField(default='male', max_length=200)),
                ('date_registered', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Scrumy Users',
            },
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adesokanscrumy.ScrumyUser'),
        ),
    ]
